spring.application.name=server
spring.config.import=optional:file:.env[.properties]
#database details
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}
spring.jpa.hibernate.ddl-auto=update
#security details
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}